export interface SeedFaq {
  slug: string
  question: string
  answer: string
  audience: 'rider' | 'dealer' | 'both'
  category: string
  aliases: string[]
  cta: 'buy' | 'test_ride' | 'showroom' | 'stock' | null
}

/**
 * Spec-true test corpus from published Amptron model data.
 * Admins can edit or replace these rows after seeding.
 */
export const FAQ_SEED: readonly SeedFaq[] = [
  {
    slug: 'what-is-amptron',
    question: 'What is Amptron?',
    answer:
      'Amptron Manufacturing Pvt. Ltd. builds certified, precision-assembled electric scooters. You can buy Amptron from us or from a partner showroom. Dealers stock Amptron next to the EV brands they already sell.',
    audience: 'both',
    category: 'company',
    aliases: [
      'who is amptron',
      'tell me about amptron',
      'amptron company',
      'who are you',
      'what are you',
      'what this company is about',
      'what is this company about',
      'about amptron',
    ],
    cta: 'buy',
  },
  {
    slug: 'which-models',
    question: 'Which Amptron models are available?',
    answer:
      'Amptron currently offers two scooters: Amptron NIRA (everyday mobility) and Amptron Cruise.',
    audience: 'both',
    category: 'models',
    aliases: ['model lineup', 'scooter range', 'what scooters do you sell'],
    cta: 'buy',
  },
  {
    slug: 'nira-overview',
    question: 'What is Amptron NIRA?',
    answer:
      'Amptron NIRA is everyday electric mobility: simple to ride, simple to charge, and simple to own. It is built around a 45–55 km real-world range target, 24 km/h top speed, and about 4.0–4.5 hours to charge. Range and weight remain targets until final test-agency values are confirmed.',
    audience: 'rider',
    category: 'models',
    aliases: [
      'everyday scooter',
      'nira scooter',
      'tell me about nira',
      'storm scooter',
      'tell me about storm',
      'what is amptron storm',
    ],
    cta: 'test_ride',
  },
  {
    slug: 'cruise-overview',
    question: 'What is Amptron Cruise?',
    answer:
      'Amptron Cruise is the long-range flagship for all-day rides. It has a 150 km certified range, 80 km/h top speed, and a 4.5 hour charge time.',
    audience: 'rider',
    category: 'models',
    aliases: ['flagship scooter', 'cruise scooter', 'long range scooter'],
    cta: 'test_ride',
  },
  {
    slug: 'nira-range',
    question: 'What is the range of Amptron NIRA?',
    answer:
      'Amptron NIRA is designed around a 45–55 km real-world range target for everyday local travel. A controlled test range target is up to approximately 55–65 km. These are not certified Rule 126 figures until a test agency confirms them.',
    audience: 'rider',
    category: 'specs',
    aliases: [
      'nira km',
      'how far does nira go',
      'nira range per charge',
      'storm km',
      'how far does storm go',
      'certified range of amptron storm',
    ],
    cta: null,
  },
  {
    slug: 'cruise-range',
    question: 'What is the certified range of Amptron Cruise?',
    answer: 'Amptron Cruise has a certified range of 150 km per charge.',
    audience: 'rider',
    category: 'specs',
    aliases: ['cruise km', 'how far does cruise go', 'cruise range per charge'],
    cta: null,
  },
  {
    slug: 'nira-speed',
    question: 'What is the top speed of Amptron NIRA?',
    answer:
      'Amptron NIRA has a top speed of 24 km/h, intended for the applicable low-speed electric two-wheeler category pending testing-agency verification.',
    audience: 'rider',
    category: 'specs',
    aliases: [
      'nira km/h',
      'nira maximum speed',
      'storm km/h',
      'storm maximum speed',
    ],
    cta: null,
  },
  {
    slug: 'cruise-speed',
    question: 'What is the top speed of Amptron Cruise?',
    answer: 'Amptron Cruise has a top speed of 80 km/h.',
    audience: 'rider',
    category: 'specs',
    aliases: ['cruise km/h', 'cruise maximum speed'],
    cta: null,
  },
  {
    slug: 'nira-charge',
    question: 'How long does Amptron NIRA take to charge?',
    answer:
      'Amptron NIRA charges in about 4.0–4.5 hours from a household socket. You can remove the battery and charge indoors, or charge with the battery installed.',
    audience: 'rider',
    category: 'charging',
    aliases: [
      'nira charging time',
      'nira charger hours',
      'storm charging time',
      'storm charger hours',
    ],
    cta: null,
  },
  {
    slug: 'cruise-charge',
    question: 'How long does Amptron Cruise take to charge?',
    answer: 'Amptron Cruise charges in 4.5 hours.',
    audience: 'rider',
    category: 'charging',
    aliases: ['cruise charging time', 'cruise charger hours'],
    cta: null,
  },
  {
    slug: 'nira-battery',
    question: 'What battery does Amptron NIRA use?',
    answer:
      'Amptron NIRA uses a removable underfloor LFP lithium battery of about 1.54 kWh / 30Ah, at 51.2V nominal (48V class), with a 240W continuous BLDC hub motor.',
    audience: 'rider',
    category: 'specs',
    aliases: [
      'nira battery capacity',
      'nira motor',
      'storm battery capacity',
      'storm motor',
    ],
    cta: null,
  },
  {
    slug: 'cruise-battery',
    question: 'What battery does Amptron Cruise use?',
    answer:
      'Amptron Cruise uses a 3.4 kWh advanced lithium-ion pack at 72V, with a 3200W BLDC hub motor.',
    audience: 'rider',
    category: 'specs',
    aliases: ['cruise battery capacity', 'cruise motor'],
    cta: null,
  },
  {
    slug: 'nira-payload',
    question: 'What is the payload of Amptron NIRA?',
    answer:
      'Amptron NIRA has a 140 kg payload. Kerb weight is a target of about 68–72 kg including the battery, and vehicle weight excluding the battery is a target of 56 kg or less, pending confirmation.',
    audience: 'rider',
    category: 'specs',
    aliases: [
      'nira weight',
      'nira carrying capacity',
      'storm weight',
      'storm carrying capacity',
    ],
    cta: null,
  },
  {
    slug: 'cruise-payload',
    question: 'What is the payload of Amptron Cruise?',
    answer: 'Amptron Cruise has a 155 kg payload and a 102 kg kerb weight.',
    audience: 'rider',
    category: 'specs',
    aliases: ['cruise weight', 'cruise carrying capacity'],
    cta: null,
  },
  {
    slug: 'how-to-buy',
    question: 'How do I buy an Amptron scooter?',
    answer:
      'Buy Amptron from us, or find a partner showroom near you. Both paths sell the same certified scooters.',
    audience: 'rider',
    category: 'buying',
    aliases: ['purchase scooter', 'order amptron', 'buy online', 'how to purchase'],
    cta: 'buy',
  },
  {
    slug: 'why-buy-amptron',
    question: 'Why should I buy an Amptron scooter?',
    answer:
      'Amptron is built for everyday riders who want dependable electric mobility without unnecessary complexity. Certified range you can plan around, practical specs, and service and spares behind the machine. You should not have to pay for things you do not need.',
    audience: 'rider',
    category: 'buying',
    aliases: [
      'why buy amptron',
      'why should i buy',
      'why do i need to buy',
      'why purchase',
      'why choose amptron',
      'why amptron',
      'why i need to buy',
    ],
    cta: 'test_ride',
  },
  {
    slug: 'why-buy-direct',
    question: 'Why buy Amptron directly?',
    answer:
      'You do not have to buy only from Amptron. The same certified scooter and warranty framework apply whether you buy from us or a partner showroom. Buy direct if you want Amptron to ship to your city. Visit a showroom if you prefer a local handover or test ride first.',
    audience: 'rider',
    category: 'buying',
    aliases: [
      'why buy from you',
      'why have to buy from you',
      'why must i buy from you',
      'why only from amptron',
      'why buy direct',
      'why from amptron only',
    ],
    cta: 'showroom',
  },
  {
    slug: 'test-ride',
    question: 'Can I book a test ride?',
    answer:
      'Yes. Book a test ride with Amptron, or visit a partner showroom. Tell us the model (NIRA or Cruise) and your city.',
    audience: 'rider',
    category: 'buying',
    aliases: [
      'test drive',
      'trial ride',
      'book a ride',
      'test ride book karna hai',
      'test ride kaise book karein',
      'test drive chahiye',
      'test chalana hai',
      'test ride available hai',
      'test ride ela book cheyyali',
    ],
    cta: 'test_ride',
  },
  {
    slug: 'find-showroom',
    question: 'Where can I find an Amptron showroom?',
    answer:
      'Use Find a Showroom on the Amptron site to locate a partner showroom. You can also buy Amptron from us directly.',
    audience: 'rider',
    category: 'buying',
    aliases: [
      'dealer near me',
      'showroom locator',
      'nearest dealer',
      'dealer kahan hai',
      'showroom kahan hai',
      'nearest showroom',
      'dealer dhundna hai',
      'mere paas dealer',
      'showroom kaha milega',
      'dealer ela vundadu',
      'showroom ela choodalani',
    ],
    cta: 'showroom',
  },
  {
    slug: 'stock-amptron',
    question: 'How can a dealer stock Amptron?',
    answer:
      'Stock Amptron next to the EV brands you already sell. Amptron is not an exclusive-territory franchise. Submit your showroom profile through Stock Amptron on the website.',
    audience: 'dealer',
    category: 'dealers',
    aliases: ['become a dealer', 'franchise', 'dealership application'],
    cta: 'stock',
  },
  {
    slug: 'exclusive-dealer',
    question: 'Do I need an exclusive Amptron dealership?',
    answer:
      'No. Dealers stock Amptron as a multi-brand line. Amptron does not require exclusive territory, and riders can still buy from Amptron directly.',
    audience: 'dealer',
    category: 'dealers',
    aliases: ['exclusive franchise', 'only amptron dealers', 'cut out dealers'],
    cta: 'stock',
  },
  {
    slug: 'warranty',
    question: 'What is the Amptron warranty?',
    answer:
      'Vehicle components are covered as per the signed sales or dealership policy and model-specific terms. Battery claims need charge-cycle and usage diagnostics through authorized service partners. Details are on the Amptron warranty page.',
    audience: 'both',
    category: 'warranty',
    aliases: ['battery warranty', 'service warranty', 'claims'],
    cta: null,
  },
  {
    slug: 'nira-features',
    question: 'What features does Amptron NIRA include?',
    answer:
      'Amptron NIRA includes a simple digital dashboard, reverse assist, side-stand motor cut-off, LED lighting, USB charging, mechanical steering and battery locks, a remote anti-theft alarm, regenerative braking support, and under-seat storage. It does not require a touchscreen, app, or subscription.',
    audience: 'rider',
    category: 'features',
    aliases: [
      'nira equipment',
      'nira accessories',
      'storm equipment',
      'storm accessories',
    ],
    cta: 'test_ride',
  },
  {
    slug: 'cruise-features',
    question: 'What features does Amptron Cruise include?',
    answer:
      'Amptron Cruise includes cruise control, a smart dashboard with telemetry, reverse mode, keyless proximity unlock, a wide floorboard and pillion comfort kit, and remote diagnostics readiness.',
    audience: 'rider',
    category: 'features',
    aliases: ['cruise equipment', 'cruise accessories'],
    cta: 'test_ride',
  },
  {
    slug: 'nira-brakes',
    question: 'What brakes does Amptron NIRA use?',
    answer:
      'Amptron NIRA uses a hydraulic disc at the front and a mechanical drum at the rear.',
    audience: 'rider',
    category: 'specs',
    aliases: ['nira braking', 'nira cbs', 'storm braking', 'storm cbs'],
    cta: null,
  },
  {
    slug: 'most-popular',
    question: 'Which Amptron scooter is most popular?',
    answer:
      'Amptron NIRA is the everyday Amptron: a 45–55 km real-world range target and 24 km/h, built for local travel, apartment charging and simple ownership.',
    audience: 'rider',
    category: 'models',
    aliases: ['best selling', 'recommended model', 'which scooter should I buy'],
    cta: 'test_ride',
  },
  {
    slug: 'home-charging',
    question: 'Can I charge Amptron scooters at home?',
    answer:
      'Yes. Amptron chargers accept AC 180–265V, 50Hz household input. Charge times are about 4.0–4.5 hours for NIRA and 4.5 hours for Cruise.',
    audience: 'rider',
    category: 'charging',
    aliases: ['household charging', 'plug in at home', 'charger voltage'],
    cta: null,
  },
  {
    slug: 'model-pricing',
    question: 'How much do Amptron scooters cost?',
    answer:
      'Starting ex-showroom prices are indicative until booking: Amptron NIRA at ₹69,990 and Amptron Cruise at ₹1,34,990. EMI estimates are on each model page.',
    audience: 'rider',
    category: 'buying',
    aliases: [
      'price',
      'cost',
      'how much is nira',
      'how much is storm',
      'ex showroom price',
      'price kya hai',
      'kitna paisa',
      'kitne mein milega',
      'scooter ka daam',
      'nira ka price',
      'storm ka price',
      'cruise ka price',
      'scooter price',
      'rate kya hai',
    ],
    cta: 'buy',
  },
  {
    slug: 'emi-financing',
    question: 'Can I buy an Amptron scooter on EMI?',
    answer:
      'Yes. Each model page shows an indicative EMI (9.99% over 36 months, ₹0 down). Lender terms vary at checkout or through a partner showroom.',
    audience: 'rider',
    category: 'buying',
    aliases: [
      'finance',
      'monthly payment',
      'loan',
      'installment',
      'kist mein milega',
      'emi kya hai',
      'loan pe milega',
      'finance karna hai',
      'monthly installment',
      'kist kitni hogi',
    ],
    cta: 'buy',
  },
  {
    slug: 'which-model-to-choose',
    question: 'Which Amptron scooter should I choose?',
    answer:
      'Choose by your daily route. Amptron NIRA (45–55 km real-world target, 24 km/h) is everyday local travel with a removable underfloor battery. Amptron Cruise (150 km, 80 km/h) is for longer all-day rides. Compare both on the Models page.',
    audience: 'rider',
    category: 'models',
    aliases: [
      'which one should I buy',
      'best model for me',
      'nira or cruise',
      'choose a scooter',
      'help me choose',
      'recommend a model',
      'which scooter should I choose',
    ],
    cta: 'test_ride',
  },
  {
    slug: 'compare-models',
    question: 'How do I compare Amptron NIRA and Cruise?',
    answer:
      'Open the Models page or any model detail page and use the compare table. It lines up published range, speed, charge time, battery, motor, brakes, weight, starting price, and EMI side by side.',
    audience: 'rider',
    category: 'models',
    aliases: ['comparison table', 'spec comparison', 'difference between models'],
    cta: null,
  },
  {
    slug: 'certified-range-meaning',
    question: 'What does certified range mean on Amptron scooters?',
    answer:
      'Certified range is the published per-charge figure on the spec sheet. Amptron Cruise has a 150 km certified range. Amptron NIRA currently publishes a 45–55 km real-world range target until test-agency confirmation. Real-world range depends on load, terrain, and temperature.',
    audience: 'rider',
    category: 'specs',
    aliases: ['real world range', 'actual range', 'how far can I go'],
    cta: null,
  },
  {
    slug: 'running-cost-savings',
    question: 'How much does it cost to run an Amptron scooter?',
    answer:
      'Use the Ownership calculator on the Amptron site to compare running cost, service, and five-year ownership against a petrol scooter. Enter your daily kilometres, petrol price, and electricity rate for an indicative result you can adjust.',
    audience: 'rider',
    category: 'buying',
    aliases: ['running cost', 'savings calculator', 'petrol vs electric', 'tco'],
    cta: 'buy',
  },
  {
    slug: 'service-locations',
    question: 'Where can I service my Amptron scooter?',
    answer:
      'Authorized partner showrooms handle sales and service. Use Find a Showroom to locate one by state and city. You can also raise a request through Contact Support on the site.',
    audience: 'rider',
    category: 'ownership',
    aliases: ['service centre', 'workshop', 'repair', 'maintenance'],
    cta: 'showroom',
  },
  {
    slug: 'spare-parts',
    question: 'Are Amptron spare parts available?',
    answer:
      'Yes. Parts supply is part of the product. Partner showrooms stock service kits, and dealers receive spare stocking guidance when they join the network.',
    audience: 'both',
    category: 'ownership',
    aliases: ['spares', 'parts availability', 'replacement parts'],
    cta: 'showroom',
  },
  {
    slug: 'warranty-claim',
    question: 'How do I raise an Amptron warranty claim?',
    answer:
      'Start with the partner showroom where you bought the scooter, or contact Amptron support. Vehicle claims follow your signed sales or dealership policy. Battery claims need charge-cycle and usage diagnostics through an authorized service partner. Details are on the Amptron warranty page.',
    audience: 'both',
    category: 'warranty',
    aliases: ['warranty process', 'claim battery', 'warranty ticket'],
    cta: null,
  },
  {
    slug: 'direct-vs-showroom',
    question: 'Is there a difference between buying direct and from a showroom?',
    answer:
      'No difference in the scooter. Both paths sell the same Amptron NIRA and Cruise, with the same warranty framework. Buy from Amptron directly, or visit a partner showroom if you prefer a local handover and test ride.',
    audience: 'rider',
    category: 'buying',
    aliases: ['buy online vs dealer', 'direct purchase', 'same scooter'],
    cta: 'buy',
  },
  {
    slug: 'direct-delivery',
    question: 'Does Amptron deliver scooters to my city?',
    answer:
      'Amptron ships direct anywhere we can service. When you buy from us, tell us your city during booking. If you prefer a local handover, use Find a Showroom for a partner near you.',
    audience: 'rider',
    category: 'buying',
    aliases: ['home delivery', 'ship to my city', 'delivery available'],
    cta: 'buy',
  },
  {
    slug: 'battery-safety',
    question: 'Are Amptron batteries safe?',
    answer:
      'Amptron packs use a BMS with voltage, current and temperature protection. NIRA uses a removable LFP pack. Cruise uses an advanced lithium-ion pack at 72V.',
    audience: 'rider',
    category: 'specs',
    aliases: ['battery safety', 'ais 156', 'bms', 'fire safe'],
    cta: null,
  },
  {
    slug: 'nira-vs-cruise',
    question: 'What is the difference between Amptron NIRA and Cruise?',
    answer:
      'Amptron NIRA (45–55 km real-world target, 24 km/h, about 1.54 kWh) is everyday local mobility with a removable underfloor LFP battery. Amptron Cruise (150 km, 80 km/h, 3.4 kWh) is the long-range flagship with dual disc brakes, cruise control, and a wider floorboard. NIRA suits short neighbourhood trips; Cruise suits longer all-day rides.',
    audience: 'rider',
    category: 'models',
    aliases: [
      'nira or cruise',
      'cruise vs nira',
      'storm or cruise',
      'cruise vs storm',
      'flagship vs everyday',
    ],
    cta: 'test_ride',
  },
  {
    slug: 'dealer-onboarding',
    question: 'What happens after I apply to stock Amptron?',
    answer:
      'Submit your showroom profile through Stock Amptron. An Amptron relationship manager reviews your EV retail footprint and contacts you within 2 business days. Onboarding covers product training, spare stocking, and service escalation before you receive inventory.',
    audience: 'dealer',
    category: 'dealers',
    aliases: [
      'dealer application timeline',
      'how long to onboard',
      'after applying',
    ],
    cta: 'stock',
  },
  {
    slug: 'dealer-support',
    question: 'What support do Amptron dealers receive?',
    answer:
      'Dealers get product training, spare stocking guidance, service escalation paths, warranty swap support, parts supply, and a relationship manager as they scale Amptron alongside other EV brands.',
    audience: 'dealer',
    category: 'dealers',
    aliases: ['dealer benefits', 'relationship manager', 'dealer training'],
    cta: 'stock',
  },
  {
    slug: 'contact-support',
    question: 'How do I contact Amptron support?',
    answer:
      'Use Contact Support on the Amptron site, or the support link on the warranty page. For warranty escalation, owners and dealers can raise tickets through the same channel. Dealer applications go through Stock Amptron on the homepage.',
    audience: 'both',
    category: 'company',
    aliases: ['customer support', 'help desk', 'phone number', 'email support'],
    cta: null,
  },
  {
    slug: 'ride-modes',
    question: 'What ride modes does Amptron NIRA have?',
    answer:
      'Amptron NIRA does not use Eco, City, and Power ride modes. It is designed around simple, predictable local riding without extra mode switching.',
    audience: 'rider',
    category: 'features',
    aliases: ['eco city power', 'nira modes', 'storm modes', 'riding modes'],
    cta: 'test_ride',
  },
  {
    slug: 'regenerative-braking',
    question: 'Does Amptron have regenerative braking?',
    answer:
      'Yes. Regenerative braking is specified on Amptron NIRA and Cruise. It sends kinetic energy back to the battery during deceleration.',
    audience: 'rider',
    category: 'features',
    aliases: ['regen braking', 'energy recovery', 'regen'],
    cta: null,
  },
  {
    slug: 'cruise-brakes',
    question: 'What brakes does Amptron Cruise use?',
    answer: 'Amptron Cruise uses dual disc brakes with CBS.',
    audience: 'rider',
    category: 'specs',
    aliases: ['cruise braking', 'cruise cbs', 'dual disc'],
    cta: null,
  },
  {
    slug: 'colours-available',
    question: 'What colours are available for Amptron scooters?',
    answer:
      'Colours vary by model. NIRA is available in Pearl Ivory, Sage Green, Matte Grey and Midnight Black. Cruise is available in Graphite Grey and Midnight Navy. See each model page for the current palette.',
    audience: 'rider',
    category: 'models',
    aliases: ['color options', 'paint colours', 'available colours'],
    cta: 'buy',
  },

  // -------------------------------------------------------------------------
  // Model-less summary FAQs
  // Catch "what is the range?" / "kitna range hai" without a two-way tie.
  // -------------------------------------------------------------------------
  {
    slug: 'range-all-models',
    question: 'What is the range of Amptron scooters?',
    answer:
      'Range by model: Amptron NIRA 45–55 km real-world target, Amptron Cruise 150 km certified. NIRA figures await test-agency confirmation. All charge from a household socket.',
    audience: 'rider',
    category: 'specs',
    aliases: [
      'how far can it go',
      'range per charge',
      'kitna range',
      'kitna range hai',
      'range kya hai',
      'ek charge mein kitna',
      'ek charge mein kitne km',
      'ela untundi range',
      'scooter range',
      'overall range',
    ],
    cta: null,
  },
  {
    slug: 'speed-all-models',
    question: 'What is the top speed of Amptron scooters?',
    answer: 'Top speed by model: Amptron NIRA 24 km/h, Amptron Cruise 80 km/h.',
    audience: 'rider',
    category: 'specs',
    aliases: [
      'maximum speed',
      'how fast',
      'top speed',
      'kitni speed',
      'speed kya hai',
      'top speed kitni hai',
      'fast kitna hai',
      'max speed',
    ],
    cta: null,
  },
  {
    slug: 'charge-time-all-models',
    question: 'How long do Amptron scooters take to charge?',
    answer:
      'Charge time by model: Amptron NIRA about 4.0–4.5 hours, Amptron Cruise 4.5 hours. All models charge on a standard AC 180-265V household socket.',
    audience: 'rider',
    category: 'charging',
    aliases: [
      'charging time',
      'how long to charge',
      'kitni der',
      'kitna time lagta hai',
      'charge karne mein kitna time',
      'kab tak charge hoga',
      'charge duration',
      'charger hours',
      'full charge kitne ghante',
    ],
    cta: null,
  },
  {
    slug: 'battery-all-models',
    question: 'What battery do Amptron scooters use?',
    answer:
      'Battery by model: NIRA uses a removable underfloor LFP pack of about 1.54 kWh / 30Ah (51.2V nominal, 240W continuous BLDC). Cruise uses 3.4 kWh advanced lithium-ion (72V, 3200W BLDC). All packs have a BMS.',
    audience: 'rider',
    category: 'specs',
    aliases: [
      'battery capacity',
      'battery type',
      'kwh',
      'battery size',
      'pack size',
      'battery kya hai',
      'battery kitne ki',
      'lithium battery',
    ],
    cta: null,
  },
  {
    slug: 'payload-all-models',
    question: 'What is the payload capacity of Amptron scooters?',
    answer:
      'Payload by model: Amptron NIRA 140 kg (kerb weight target about 68–72 kg including battery), Amptron Cruise 155 kg (kerb weight 102 kg).',
    audience: 'rider',
    category: 'specs',
    aliases: [
      'weight capacity',
      'carrying capacity',
      'load capacity',
      'max load',
      'kitna weight carry',
      'kitna bojh',
      'payload kya hai',
    ],
    cta: null,
  },
  {
    slug: 'brakes-all-models',
    question: 'What brakes do Amptron scooters use?',
    answer:
      'Brake setup by model: Amptron NIRA hydraulic disc and mechanical drum. Amptron Cruise dual disc with CBS.',
    audience: 'rider',
    category: 'specs',
    aliases: [
      'braking system',
      'what brakes',
      'cbs brakes',
      'disc brakes',
      'drum brakes',
      'brake type',
      'brakes kya hain',
    ],
    cta: null,
  },
]
